### ISSUE TITLE
TypeError: Argument 1 passed to Rebilly\Rest\Resource::populate() must be of the type array, string given

### ISSUE THREAD

**Issue by ae94** [Rebilly/rebilly-php#272]
When using the createPaymentCard function (with token and customerId), PHP is running into an exception when populating the request result:

TypeError: Argument 1 passed to Rebilly\Rest\Resource::populate() must be of the type array, string given

Stack attached.
![bildschirmfoto 2018-06-14 um 21 39 19](https://user-images.githubusercontent.com/8861555/41434267-71a2ef40-701b-11e8-96d7-2eac2e81ed03.png)

**Comment by adamaltman** [comment]
Thank you.  The SDK expects a location header.  We had recently changed a behavior in the API where you will only be able to create 1 payment card per customer per pan (card number).
