### ISSUE TITLE
Creating coupon fails

### ISSUE THREAD

**Issue by ae94** [Rebilly/rebilly-php#278]
In entities/coupons/coupon.php function createRestriction. $data is beeing mapped there, but it contains objects, not arrays

**Comment by XaosSintez** [comment]
@ae94 Can you please provide your code example?

**Comment by ae94** [comment]
@XaosSintez cant find the code right now, but here's the link of my (workaround) fix for now, this may helps:
https://github.com/Mandaris-LLC/rebilly-php/commit/0675de9a8968d37a71de89267b952147bc67cc52

Once Im back in my office I'll send the code.

**Comment by XaosSintez** [comment]
@ae94 Thank you, waiting for your code, because i'm not sure, what exactly is wrong. 
`$data` must be an array. But if you will show your code example, it may help me to understand the issue.

**Comment by ae94** [comment]
Couldn't reproduce the issue, will close, thanks
