### ISSUE TITLE
Coupon Codes not showing when the coupon has restriction of: restrict-to-products

### ISSUE THREAD

**Issue by jamesclavel** [Rebilly/rebilly-php#484]
currently using: SDK v2.12.0

`PHP Fatal error:  Uncaught DomainException: Unexpected type. Only discounts-per-redemption,redemptions-per-customer,restrict-to-invoices,restrict-to-plans,restrict-to-subscriptions,total-redemptions,minimum-order-amount types support in /rebilly/client-php/src/Entities/Coupons/Restriction.php:99`

Solution: 
- create `RestrictToProducts.php` inside `/rebilly/client-php/src/Entities/Coupons/Restrictions/`
- update `/rebilly/client-php/src/Entities/Coupons/Restriction.php` to accept type: `restrict-to-products`

Hoping in the next release this will be added. thanks!

**Comment by XaosSintez** [comment]
Thank you for noticing the issue! I will fix it.

**Comment by XaosSintez** [comment]
@jamesclavel The issue was fixed and the fix will be included to next release. Thank you!
