### ISSUE TITLE
Need to get the "type" of invoice

### ISSUE THREAD

**Issue by jamesclavel** [Rebilly/rebilly-php#486]
Hi there, not really an issue but if you can add the "getType()" method from the "/Entities/Invoice.php" to return the invoice "type" attribute so we can get the invoice type when querying a particular invoice. We're using it for some reporting and we'd like to have that option and doesn't break our code when updating to the new SDK in the future.

Invoice Types: `Renewal`, `Initial`, `One Time`, etc...

Please see attached file for the invoice types. Appreciate it!

![Screen Shot 2021-07-23 at 1 48 27 PM](https://user-images.githubusercontent.com/6337689/126763377-124ca66d-a12d-4966-acff-c80897cb4052.jpg)

**Comment by ashkarpetin** [comment]
Hi, type property was added.

**Comment by jamesclavel** [comment]
Thanks, appreciate it.
