### ISSUE TITLE
Specify the Paginator template parameter to annotations of pagination methods

### ISSUE THREAD

**Issue by nevmerzhitsky** [Rebilly/rebilly-php#668]
SDK version: 3.0.0

It will be great for introspection to have a specified template parameter of the class `Paginator` in all Api-class methods whose return the `Paginator` instance: `CustomersApi::getAllPaginator()`, `CustomersApi::getAllEddSearchResultsPaginator()` and so on like `*Api::getAll*Paginator()`.

I mean we need just smth like this:

```php
/**
 * @return Paginator<EddSearchResult>
 */
public function getAllEddSearchResultsPaginator(
    string $id,
    ?int $limit = null,
    ?int $offset = null,
): Paginator {
    ...
}
```

**Comment by justnero** [comment]
Hi @nevmerzhitsky! Thank you for raising this issue.

You can find it implemented in version [3.1.0](https://github.com/Rebilly/rebilly-php/releases/tag/3.1.0).
