### ISSUE TITLE
Feature Suggestion: Add "expand" Parameter to refund method

### ISSUE THREAD

**Issue by Anemoiaa** [Rebilly/rebilly-php#672]
We propose adding an "expand" parameter to the refund method. This improvement,  would allow users to specify additional resources to include in the response, reducing the number of requests needed to update information after a transaction refund.

**Example Usage**
`$newTransaction = $coreService->transactions()->refund(id: 1, expand: 'invoices,parentTransaction');
`

**Comment by ashkarpetin** [comment]
Hello! Thank you for creating an issue. This is request is related to API change. Our API documentation is located in another [repository](https://github.com/Rebilly/api-definitions). So any API related requests should be opened in that repository.
